### ISSUE TITLE
Inline code spans not working

### ISSUE THREAD

**Issue by jdimeo** [murank/redmine_kramdown_formatter#1]
Thank you for making this plugin! A lifesaver for supporting Markdown on JRuby.

Inline code spans, like this:
```
This is some `code`.
```
Appear to render as plain text currently.

I tracked it down to this part of the code:
```
def convert_codespan_with_redmine(el, indent)
	lang = el.options[:lang]

if lang.present?
	"<code class=\"#{CGI.escapeHTML(lang)} syntaxhl\">" +
		Redmine::SyntaxHighlighting.highlight_by_language(el.value, lang) +
	"</code>"
else
	CGI.escapeHTML(el.value)
end
```

Shouldn't the "else" be this?
```
else
	"<code>" + CGI.escapeHTML(el.value) + "</code>"
end
```
so that regular ole' inline code spans without any language defined still get rendered with `<code>` tags?

**Comment by murank** [comment]
Thank you for your reporting.
Your guess is probably right.

I'd like to fix it, but  unfortunately I hardly have enough time to do it...
So if you can create a PR, I will welcome it :)

**Comment by jdimeo** [comment]
@murank created as PR #2

**Comment by murank** [comment]
Great work!!!
I merged it!
